AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'realtor-api-2

  Sample SAM Template for realtor-api-2

  '
Globals:
  Function:
    Timeout: 3
Resources:
  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://realtor-api-prod/44d073c537f85fb4ad27cb0c5e1a8b11
      Handler: login.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
      - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /login
            Method: post
      Environment:
        Variables:
          NODE_OPTIONS: ' --enable-source-maps'
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
        - login.ts
        Minify: true
        Sourcemap: true
        Target: es2020
      SamResourceId: LoginFunction
  SignupFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://realtor-api-prod/1d383dfc90d58b2fc5a8cc81857d65c9
      Handler: signup.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
      - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /signup
            Method: post
      Environment:
        Variables:
          NODE_OPTIONS: ' --enable-source-maps'
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
        - signup.ts
        Minify: true
        Sourcemap: true
        Target: es2020
      SamResourceId: SignupFunction
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UserTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
    Metadata:
      SamResourceId: UserTable
  HomeTableV2:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: HomeTableV3
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: creator_id
        AttributeType: S
      - AttributeName: zpid
        AttributeType: S
      KeySchema:
      - AttributeName: creator_id
        KeyType: HASH
      - AttributeName: zpid
        KeyType: RANGE
    Metadata:
      SamResourceId: HomeTableV2
  UnsplashFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://realtor-api-prod/22d4ad2e81e58aaddd03663d61313fdd
      Handler: unsplash-proxy.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
      - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /unsplash-proxy
            Method: get
      Environment:
        Variables:
          NODE_OPTIONS: ' --enable-source-maps'
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
        - unsplash-proxy.ts
        Minify: true
        Sourcemap: true
        Target: es2020
      SamResourceId: UnsplashFunction
  AddFavoritesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://realtor-api-prod/34ddc818437eb8284f0258d5cfde8d25
      Handler: addFavoriteHomes.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
      - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /favorites
            Method: post
      Environment:
        Variables:
          NODE_OPTIONS: ' --enable-source-maps'
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
        - addFavoriteHomes.ts
        Minify: true
        Sourcemap: true
        Target: es2020
      SamResourceId: AddFavoritesFunction
  GetFavoritesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://realtor-api-prod/17ae067977065762d712c11e67119e5e
      Handler: getFavoriteHomes.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
      - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /favorites
            Method: get
      Environment:
        Variables:
          NODE_OPTIONS: ' --enable-source-maps'
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
        - getFavoriteHomes.ts
        Minify: true
        Sourcemap: true
        Target: es2020
      SamResourceId: GetFavoritesFunction
