export const homeTestData = {
  listingProvider: null,
  buildingPermits: null,
  propertyTaxRate: 0.77,
  contact_recipients: [
    {
      agent_reason: 1,
      zpro: null,
      recent_sales: 1,
      review_count: 60,
      display_name: "Dennis Poldnev",
      zuid: "X1-ZUzejb94q39ssp_aau4d",
      rating_average: 4.9,
      badge_type: "Premier Agent",
      phone: { prefix: "882", areacode: "310", number: "7802" },
      image_url:
        "https://photos.zillowstatic.com/h_n/ISfciel1pdj1eb0000000000.jpg",
    },
  ],
  solarPotential: {
    sunScore: 85.75,
    solarFactor: 2.8,
    buildFactor: 70.4,
    climateFactor: 7.14,
    electricityFactor: 5.42,
  },
  longitude: -118.47468,
  countyFIPS: "06037",
  cityId: 26964,
  timeOnZillow: "72 days",
  url: "/homedetails/737-Raymond-Ave-Santa-Monica-CA-90405/20482753_zpid/",
  zestimate: 2885500,
  imgSrc:
    "https://photos.zillowstatic.com/fp/4887644480f1a365ac3abde764c3b907-p_d.jpg",
  zpid: 20482753,
  zipcode: "90405",
  livingAreaValue: 1800,
  zestimateLowPercent: "5",
  isListedByOwner: false,
  propertyTypeDimension: "Single Family",
  resoFacts: {
    hasAttachedProperty: false,
    frontageType: null,
    poolFeatures: ["Heated And Filtered", "In Ground"],
    flooring: ["Hardwood", "Painted/Stained"],
    foundationDetails: {},
    accessibilityFeatures: null,
    hasGarage: false,
    hasPetsAllowed: null,
    bodyType: null,
    topography: null,
    landLeaseExpirationDate: null,
    hasAdditionalParcels: false,
    waterViewYN: null,
    atAGlanceFacts: [
      { factLabel: "Type", factValue: "Residential" },
      { factLabel: "Year Built", factValue: "1925" },
      { factLabel: "Heating", factValue: "Central" },
      { factLabel: "Cooling", factValue: "Air Conditioning" },
      { factLabel: "Parking", factValue: "1 Open Parking space" },
      { factLabel: "Lot", factValue: "6,464 sqft" },
      { factLabel: "Days on Zillow", factValue: "72 Days" },
      { factLabel: "Price/sqft", factValue: "$1,611" },
      { factLabel: "Buyer's Agent Fee", factValue: "2.5" },
      { factLabel: "Offer Review Date", factValue: null },
    ],
    offerReviewDate: null,
    aboveGradeFinishedArea: null,
    view: ["Tree Top"],
    buyerAgencyCompensationType: "%",
    rooms: [
      {
        level: null,
        dimensions: null,
        features: null,
        roomFeatures: null,
        roomArea: null,
        roomAreaSource: null,
        roomLength: null,
        width: null,
        roomDescription: null,
        roomWidth: null,
        roomLevel: "Upper",
        roomLengthWidthUnits: null,
        roomLengthWidthSource: null,
        roomDimensions: null,
        roomAreaUnits: null,
        roomType: "Bedroom",
        length: null,
        description: null,
        area: null,
      },
      {
        level: null,
        dimensions: null,
        features: null,
        roomFeatures: ["Marble Counters"],
        roomArea: null,
        roomAreaSource: null,
        roomLength: null,
        width: null,
        roomDescription: null,
        roomWidth: null,
        roomLevel: null,
        roomLengthWidthUnits: null,
        roomLengthWidthSource: null,
        roomDimensions: null,
        roomAreaUnits: null,
        roomType: "Kitchen",
        length: null,
        description: null,
        area: null,
      },
    ],
    carportSpaces: null,
    cityRegion: "Santa Monica",
    mainLevelBathrooms: null,
    hasPrivatePool: true,
    associationFeeIncludes: null,
    waterSource: null,
    exteriorFeatures: {},
    coveredSpaces: null,
    inclusions: null,
    hasFireplace: false,
    zoningDescription: null,
    garageSpaces: null,
    sewer: null,
    elevationUnits: null,
    exclusions: null,
    mainLevelBedrooms: null,
    numberOfUnitsVacant: null,
    hasWaterfrontView: null,
    listAOR: null,
    lotSize: "6,464 sqft",
    entryLevel: null,
    irrigationWaterRightsAcres: null,
    greenWaterConservation: null,
    stories: 2,
    livingArea: "1,800 sqft",
    numberOfUnitsInCommunity: null,
    listingTerms: null,
    otherStructures: ["Cabana", "Detached Guest House"],
    associationFee: null,
    marketingType: null,
    greenIndoorAirQuality: null,
    greenSustainability: null,
    hasHomeWarranty: false,
    associationPhone: null,
    greenBuildingVerificationType: null,
    elementarySchool: null,
    bedrooms: 3,
    architecturalStyle: "Farm House",
    listingId: null,
    structureType: "Detached",
    interiorFeatures: ["Turnkey", "Built-Ins", "Dining Area"],
    horseAmenities: null,
    electric: null,
    developmentStatus: null,
    lotFeatures: ["Front Yard", "Sidewalks", "Yard"],
    roofType: null,
    waterSources: null,
    constructionMaterials: {},
    fireplaceFeatures: ["None"],
    doorFeatures: ["French Doors"],
    appliances: [
      "Built-In Gas",
      "Range Hood",
      "Dishwasher",
      "Range/Oven",
      "Refrigerator",
      "Dryer",
      "Washer",
    ],
    daysOnZillow: 72,
    bathroomsPartial: null,
    bathroomsHalf: 0,
    depositsAndFees: null,
    canRaiseHorses: false,
    buildingName: null,
    hasAssociation: false,
    petsMaxWeight: null,
    commonWalls: null,
    totalActualRent: null,
    additionalParcelsDescription: null,
    associationName: null,
    allowedPets: null,
    communityFeatures: null,
    tenantPays: null,
    middleOrJuniorSchool: null,
    lotSizeDimensions: null,
    roadSurfaceType: null,
    hasOpenParking: true,
    yearBuilt: 1925,
    livingAreaRangeUnits: null,
    irrigationWaterRightsYN: null,
    bathroomsFull: 3,
    horseYN: null,
    incomeIncludes: null,
    highSchool: null,
    leaseTerm: null,
    elevation: null,
    cropsIncludedYN: null,
    attic: null,
    subdivisionName: null,
    windowFeatures: null,
    ownership: null,
    woodedArea: null,
    middleOrJuniorSchoolDistrict: null,
    associationPhone2: null,
    buyerAgencyCompensation: "2.5",
    heating: ["Central"],
    frontageLength: null,
    virtualTourURLUnbranded: null,
    associationAmenities: null,
    propertySubType: ["Residential"],
    hasCooling: true,
    belowGradeFinishedArea: null,
    hasElectricOnProperty: null,
    foundationArea: null,
    zoning: "SMOP2*",
    hoaFee: null,
    livingAreaRange: null,
    basementYN: false,
    availabilityDate: null,
    waterBodyName: null,
    waterfrontFeatures: ["None"],
    specialListingConditions: "Standard",
    buildingAreaSource: null,
    taxAnnualAmount: 27268,
    parking: 1,
    hasView: true,
    virtualTour: "https://youtu.be/3gNfahh8G_w",
    securityFeatures: [
      "Exterior Security Lights",
      "Automatic Gate",
      "Gated",
      "Prewired",
      "Smoke Detector(s)",
      "Security Lights",
      "Alarm System",
    ],
    cooling: ["Air Conditioning"],
    entryLocation: null,
    otherFacts: {},
    levels: "Two",
    ownershipType: null,
    basement: null,
    onMarketDate: 1656039486000,
    waterView: null,
    laundryFeatures: ["Inside", "Laundry Area"],
    hasAttachedGarage: false,
    fencing: "Fenced Yard",
    spaFeatures: ["Hot Tub", "In Ground", "Heated"],
    bathrooms: 3,
    homeType: "SingleFamily",
    isSeniorCommunity: null,
    municipality: null,
    bathroomsThreeQuarter: 0,
    hasSpa: false,
    otherParking: null,
    associationFee2: null,
    parcelNumber: "4287017039",
    hasHeating: true,
    associationName2: null,
    hasRentControl: null,
    elementarySchoolDistrict: null,
    otherEquipment: null,
    parkingFeatures: ["Auto Driveway Gate", "Private"],
    buildingArea: "1,800",
    furnished: false,
    vegetation: null,
    patioAndPorchFeatures: ["Front Porch", "Covered Porch", "Deck"],
    buildingFeatures: ["Sprinkler System"],
    builderName: null,
    highSchoolDistrict: null,
    propertyCondition: "Updated/Remodeled",
    storiesTotal: null,
    yearBuiltEffective: null,
    fireplaces: null,
    bathroomsOneQuarter: 0,
    builderModel: null,
    gas: null,
    utilities: null,
    greenEnergyEfficient: null,
    landLeaseAmount: null,
    isNewConstruction: null,
    hasLandLease: false,
    pricePerSquareFoot: 1611,
    hasCarport: false,
    openParkingSpaces: null,
  },
  streetAddress: "737 Raymond Ave",
  county: null,
  taxHistory: [
    {
      time: 1630740513565,
      valueIncreaseRate: 0.010359906,
      taxIncreaseRate: 0.006805846,
      taxPaid: 27268.41,
      value: 2280645,
    },
    {
      time: 1599204513565,
      valueIncreaseRate: 0.41110852,
      taxIncreaseRate: 0,
      taxPaid: 27084.08,
      value: 2257260,
    },
    {
      time: 1567582113565,
      valueIncreaseRate: 0.019999731,
      taxIncreaseRate: 0.47111905,
      taxPaid: 27084.08,
      value: 1599636,
    },
    {
      time: 1536046113565,
      valueIncreaseRate: 0.019999728,
      taxIncreaseRate: 0,
      taxPaid: 18410.53,
      value: 1568271,
    },
    {
      time: 1504510113565,
      valueIncreaseRate: 0.24133278,
      taxIncreaseRate: 0.004376825,
      taxPaid: 18410.53,
      value: 1537521,
    },
    {
      time: 1472974113565,
      valueIncreaseRate: 0.01525,
      taxIncreaseRate: 0.24738948,
      taxPaid: 18330.3,
      value: 1238605,
    },
    {
      time: 1441351713565,
      valueIncreaseRate: 0.35555556,
      taxIncreaseRate: 0.34615302,
      taxPaid: 14694.93,
      value: 1220000,
    },
    {
      time: 1409815713565,
      valueIncreaseRate: 1.5240273,
      taxIncreaseRate: 0,
      taxPaid: 10916.24,
      value: 900000,
    },
    {
      time: 1346743713565,
      valueIncreaseRate: 0.019998169,
      taxIncreaseRate: 0,
      taxPaid: null,
      value: 356573,
    },
    {
      time: 1315121313565,
      valueIncreaseRate: 0.0075251246,
      taxIncreaseRate: 0,
      taxPaid: null,
      value: 349582,
    },
    {
      time: 1283585313565,
      valueIncreaseRate: -0.0023720802,
      taxIncreaseRate: 0,
      taxPaid: null,
      value: 346971,
    },
    {
      time: 1252049313565,
      valueIncreaseRate: 0.019995425,
      taxIncreaseRate: 0,
      taxPaid: null,
      value: 347796,
    },
    {
      time: 1220513313565,
      valueIncreaseRate: 0.019997427,
      taxIncreaseRate: 0,
      taxPaid: null,
      value: 340978,
    },
    {
      time: 1188890913565,
      valueIncreaseRate: -0.68025535,
      taxIncreaseRate: 0,
      taxPaid: null,
      value: 334293,
    },
    {
      time: 1157354913565,
      valueIncreaseRate: 0.24086413,
      taxIncreaseRate: 0,
      taxPaid: null,
      value: 1045500,
    },
    {
      time: 1125818913565,
      valueIncreaseRate: 0.040398005,
      taxIncreaseRate: 0,
      taxPaid: null,
      value: 842558,
    },
    {
      time: 1094282913565,
      valueIncreaseRate: 1.6187885,
      taxIncreaseRate: 0,
      taxPaid: null,
      value: 809842,
    },
    {
      time: 1062660513565,
      valueIncreaseRate: 0.019998021,
      taxIncreaseRate: 0,
      taxPaid: null,
      value: 309243,
    },
    {
      time: 1031124513565,
      valueIncreaseRate: 0.04038983,
      taxIncreaseRate: 0,
      taxPaid: null,
      value: 303180,
    },
    {
      time: 968052513565,
      valueIncreaseRate: 0,
      taxIncreaseRate: 0,
      taxPaid: null,
      value: 291410,
    },
  ],
  stateId: 9,
  countyId: 3101,
  timeZone: "America/Los_Angeles",
  homeType: "SINGLE_FAMILY",
  livingAreaUnits: "sqft",
  comingSoonOnMarketDate: null,
  livingArea: 1800,
  bathrooms: 3,
  annualHomeownersInsurance: 12176,
  state: "CA",
  rentZestimate: 7199,
  building: null,
  brokerId: null,
  yearBuilt: 1925,
  brokerageName: "Redfin",
  dateSold: "2019-03-26",
  price: 2899000,
  pageViewCount: 7964,
  description:
    "Your Santa Monica sanctuary awaits. This summer entertain your guests in the expansive and ultra-private backyard that feels like a resort. Cool off in the pool or unwind in the spa under the stars. Gather around the firepit year-round. This modern Farmhouse styled home is situated in desirable Ocean Park, west of Lincoln and seven blocks to the beach. It features a kitchen with high-end stainless steel appliances that opens to the living area and two bedrooms with chic-inspired bathrooms in the main home. A detached and equipped poolside studio offers an additional private escape. Stop off at one of the trendy restaurants nearby on Main St or Rose Ave and enjoy all that Westside has to offer.",
  mortgageRates: {
    arm5Rate: 4.695,
    fifteenYearFixedRate: 4.923,
    thirtyYearFixedRate: 5.227,
  },
  homeStatus: "FOR_SALE",
  homeFacts: null,
  latitude: 34.00502,
  datePosted: "2022-06-24",
  bedrooms: 3,
  nearbyHomes: [
    {
      miniCardPhotos: [
        {
          url: "https://photos.zillowstatic.com/fp/e6eb8ad71bb40ddd21db09b4dd4414fc-p_c.jpg",
        },
      ],
      zpid: 2078889692,
      longitude: -118.474815,
      address: {
        city: "Santa Monica",
        state: "CA",
        streetAddress: "731 Raymond Ave #B",
        zipcode: "90405",
      },
      price: 790200,
      homeType: "MULTI_FAMILY",
      homeStatus: "OTHER",
      currency: "USD",
      latitude: 34.004944,
    },
    {
      miniCardPhotos: [
        {
          url: "https://photos.zillowstatic.com/fp/08b61164fe0d048e638e869a1acd7197-p_c.jpg",
        },
      ],
      zpid: 2082615384,
      longitude: -118.474815,
      address: {
        city: "Santa Monica",
        state: "CA",
        streetAddress: "731 Raymond Ave APT D",
        zipcode: "90405",
      },
      price: 0,
      homeType: "APARTMENT",
      homeStatus: "OTHER",
      currency: "USD",
      latitude: 34.004944,
    },
    {
      miniCardPhotos: [
        {
          url: "https://photos.zillowstatic.com/fp/33e32e82f901bb90e3660aae76bf5d4f-p_c.jpg",
        },
      ],
      zpid: 2091509437,
      longitude: -118.474815,
      address: {
        city: "Santa Monica",
        state: "CA",
        streetAddress: "731 Raymond Ave APT A",
        zipcode: "90405",
      },
      price: 0,
      homeType: "APARTMENT",
      homeStatus: "OTHER",
      currency: "USD",
      latitude: 34.004944,
    },
    {
      miniCardPhotos: [
        {
          url: "https://photos.zillowstatic.com/fp/2cddb22d30270d53c0f8c0a05f4cd383-p_c.jpg",
        },
      ],
      zpid: 2093959412,
      longitude: -118.474815,
      address: {
        city: "Santa Monica",
        state: "CA",
        streetAddress: "731 Raymond Ave APT C",
        zipcode: "90405",
      },
      price: 798400,
      homeType: "CONDO",
      homeStatus: "OTHER",
      currency: "USD",
      latitude: 34.004944,
    },
    {
      miniCardPhotos: [
        {
          url: "https://photos.zillowstatic.com/fp/22842cc31e26c76453399d9164734673-p_c.jpg",
        },
      ],
      zpid: 2121752381,
      longitude: -118.474815,
      address: {
        city: "Santa Monica",
        state: "CA",
        streetAddress: "731 Raymond Ave",
        zipcode: "90405",
      },
      price: 0,
      homeType: "APARTMENT",
      homeStatus: "OTHER",
      currency: "USD",
      latitude: 34.004944,
    },
    {
      miniCardPhotos: [
        {
          url: "https://photos.zillowstatic.com/fp/ed1a45d91d2600dda34e34d04daa1445-p_c.jpg",
        },
      ],
      zpid: 2067389481,
      longitude: -118.47482,
      address: {
        city: "Santa Monica",
        state: "CA",
        streetAddress: "731 Raymond Ave #E",
        zipcode: "90405",
      },
      price: 0,
      homeType: "APARTMENT",
      homeStatus: "OTHER",
      currency: "USD",
      latitude: 34.004948,
    },
    {
      miniCardPhotos: [
        {
          url: "https://maps.googleapis.com/maps/api/streetview?location=729+Raymond+Ave%2C+Santa+Monica%2C+CA+90405&size=316x234&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=IhxrcvL2ET4Uyy_vPRkai9rpugU=",
        },
      ],
      zpid: 20482750,
      longitude: -118.474915,
      address: {
        city: "Santa Monica",
        state: "CA",
        streetAddress: "729 Raymond Ave",
        zipcode: "90405",
      },
      price: 1566600,
      homeType: "SINGLE_FAMILY",
      homeStatus: "OTHER",
      currency: "USD",
      latitude: 34.004883,
    },
    {
      miniCardPhotos: [
        {
          url: "https://maps.googleapis.com/maps/api/streetview?location=727+Raymond+Ave%2C+Santa+Monica%2C+CA+90405&size=316x234&key=AIzaSyARFMLB1na-BBWf7_R3-5YOQQaHqEJf6RQ&source=outdoor&&signature=atbdvBHnSP8vWTgKGwNttEuzM_Q=",
        },
      ],
      zpid: 20482749,
      longitude: -118.47498,
      address: {
        city: "Santa Monica",
        state: "CA",
        streetAddress: "727 Raymond Ave",
        zipcode: "90405",
      },
      price: 1402900,
      homeType: "SINGLE_FAMILY",
      homeStatus: "OTHER",
      currency: "USD",
      latitude: 34.004845,
    },
  ],
  monthlyHoaFee: null,
  priceHistory: [
    {
      priceChangeRate: 0.30998644374153,
      date: "2022-06-24",
      source: "CLAW",
      postingIsRental: false,
      time: 1656028800000,
      sellerAgent: null,
      showCountyLink: false,
      attributeSource: {
        infoString2: "CLAW",
        infoString3:
          "https://photos.zillowstatic.com/fp/d1d7f14ba9e5de22bbf848071a4b8b8e-zillow_web_logo_inf_11.jpg",
        infoString1: "22-171535",
      },
      pricePerSquareFoot: 1611,
      buyerAgent: null,
      event: "Listed for sale",
      price: 2899000,
    },
    {
      priceChangeRate: -0.057495741056218,
      date: "2019-03-26",
      source: "CLAW",
      postingIsRental: false,
      time: 1553558400000,
      sellerAgent: {
        name: "Nancy Osborne",
        photo: {
          url: "https://photos.zillowstatic.com/h_e/IS525bnqrz87n50000000000.jpg",
        },
        profileUrl: "/profile/nancyosbornere/",
      },
      showCountyLink: false,
      attributeSource: {
        infoString2: "CLAW",
        infoString3:
          "https://photos.zillowstatic.com/fp/4f3066f1f5cec0da94c227e529c8b89a-zillow_web_logo_inf_11.jpg",
        infoString1: "18380564",
      },
      pricePerSquareFoot: 1229,
      buyerAgent: null,
      event: "Sold",
      price: 2213000,
    },
    {
      priceChangeRate: 0,
      date: "2019-02-19",
      source: "Halton Pardee and Partners, Inc.",
      postingIsRental: false,
      time: 1550534400000,
      sellerAgent: null,
      showCountyLink: false,
      attributeSource: {
        infoString2: "Halton Pardee and Partners, Inc.",
        infoString3: null,
        infoString1: null,
      },
      pricePerSquareFoot: 1304,
      buyerAgent: null,
      event: "Pending sale",
      price: 2348000,
    },
    {
      priceChangeRate: -0.058917835671343,
      date: "2019-01-17",
      source: "Halton Pardee and Partners, Inc.",
      postingIsRental: false,
      time: 1547683200000,
      sellerAgent: null,
      showCountyLink: false,
      attributeSource: {
        infoString2: "Halton Pardee and Partners, Inc.",
        infoString3: null,
        infoString1: null,
      },
      pricePerSquareFoot: 1304,
      buyerAgent: null,
      event: "Price change",
      price: 2348000,
    },
    {
      priceChangeRate: -0.074211502782931,
      date: "2018-09-03",
      source: "Halton Pardee and Partners, Inc.",
      postingIsRental: false,
      time: 1535932800000,
      sellerAgent: null,
      showCountyLink: false,
      attributeSource: {
        infoString2: "Halton Pardee and Partners, Inc.",
        infoString3: null,
        infoString1: null,
      },
      pricePerSquareFoot: 1386,
      buyerAgent: null,
      event: "Listed for sale",
      price: 2495000,
    },
    {
      priceChangeRate: 0,
      date: "2018-08-03",
      source: "Halton Pardee and Partners, Inc.",
      postingIsRental: false,
      time: 1533254400000,
      sellerAgent: null,
      showCountyLink: false,
      attributeSource: {
        infoString2: "Halton Pardee and Partners, Inc.",
        infoString3: null,
        infoString1: null,
      },
      pricePerSquareFoot: 1497,
      buyerAgent: null,
      event: "Listing removed",
      price: 2695000,
    },
    {
      priceChangeRate: -0.069084628670121,
      date: "2018-04-05",
      source: "Halton Pardee and Partners, Inc.",
      postingIsRental: false,
      time: 1522886400000,
      sellerAgent: null,
      showCountyLink: false,
      attributeSource: {
        infoString2: "Halton Pardee and Partners, Inc.",
        infoString3: null,
        infoString1: null,
      },
      pricePerSquareFoot: 1497,
      buyerAgent: null,
      event: "Price change",
      price: 2695000,
    },
    {
      priceChangeRate: 1.3729508196721,
      date: "2018-02-15",
      source: "Halton Pardee and Partners, Inc.",
      postingIsRental: false,
      time: 1518652800000,
      sellerAgent: null,
      showCountyLink: false,
      attributeSource: {
        infoString2: "Halton Pardee and Partners, Inc.",
        infoString3: null,
        infoString1: null,
      },
      pricePerSquareFoot: 1608,
      buyerAgent: null,
      event: "Listed for sale",
      price: 2895000,
    },
    {
      priceChangeRate: 0.35555555555556,
      date: "2014-12-23",
      source: "CLAW",
      postingIsRental: false,
      time: 1419292800000,
      sellerAgent: {
        name: "Heather Stevens",
        photo: {
          url: "https://photos.zillowstatic.com/h_e/ISblaj53zscs0y1000000000.jpg",
        },
        profileUrl: "/profile/Heather-Stevens-RE/",
      },
      showCountyLink: false,
      attributeSource: {
        infoString2: "CLAW",
        infoString3:
          "https://photos.zillowstatic.com/fp/4f3066f1f5cec0da94c227e529c8b89a-zillow_web_logo_inf_11.jpg",
        infoString1: "14802933",
      },
      pricePerSquareFoot: 678,
      buyerAgent: {
        name: "Chanelle Martina",
        photo: {
          url: "https://photos.zillowstatic.com/h_e/IS9tc2kvemzz7v1000000000.jpg",
        },
        profileUrl: "/profile/chanelle-martina/",
      },
      event: "Sold",
      price: 1220000,
    },
    {
      priceChangeRate: 0.0011123470522803,
      date: "2013-08-23",
      source: "CLAW",
      postingIsRental: false,
      time: 1377216000000,
      sellerAgent: {
        name: "Ian Brooks",
        photo: {
          url: "https://photos.zillowstatic.com/h_e/ISbh7eom7xtwle0000000000.jpg",
        },
        profileUrl: "/profile/Ian-L-Brooks/",
      },
      showCountyLink: false,
      attributeSource: {
        infoString2: "CLAW",
        infoString3:
          "https://photos.zillowstatic.com/fp/4f3066f1f5cec0da94c227e529c8b89a-zillow_web_logo_inf_11.jpg",
        infoString1: "12637869",
      },
      pricePerSquareFoot: 500,
      buyerAgent: {
        name: "Heather Stevens",
        photo: {
          url: "https://photos.zillowstatic.com/h_e/ISblaj53zscs0y1000000000.jpg",
        },
        profileUrl: "/profile/Heather-Stevens-RE/",
      },
      event: "Sold",
      price: 900000,
    },
    {
      priceChangeRate: -0.043617021276596,
      date: "2013-07-31",
      source: "--",
      postingIsRental: false,
      time: 1375228800000,
      sellerAgent: null,
      showCountyLink: false,
      attributeSource: {
        infoString2: null,
        infoString3: null,
        infoString1: null,
      },
      pricePerSquareFoot: 499,
      buyerAgent: null,
      event: "Price change",
      price: 899000,
    },
    {
      priceChangeRate: -0.010526315789474,
      date: "2013-07-23",
      source: "--",
      postingIsRental: false,
      time: 1374537600000,
      sellerAgent: null,
      showCountyLink: false,
      attributeSource: {
        infoString2: null,
        infoString3: null,
        infoString1: null,
      },
      pricePerSquareFoot: 522,
      buyerAgent: null,
      event: "Price change",
      price: 940000,
    },
    {
      priceChangeRate: -0.010416666666667,
      date: "2013-06-23",
      source: "--",
      postingIsRental: false,
      time: 1371945600000,
      sellerAgent: null,
      showCountyLink: false,
      attributeSource: {
        infoString2: null,
        infoString3: null,
        infoString1: null,
      },
      pricePerSquareFoot: 528,
      buyerAgent: null,
      event: "Price change",
      price: 950000,
    },
    {
      priceChangeRate: -0.015384615384615,
      date: "2013-06-14",
      source: "--",
      postingIsRental: false,
      time: 1371168000000,
      sellerAgent: null,
      showCountyLink: false,
      attributeSource: {
        infoString2: null,
        infoString3: null,
        infoString1: null,
      },
      pricePerSquareFoot: 533,
      buyerAgent: null,
      event: "Price change",
      price: 960000,
    },
    {
      priceChangeRate: 0,
      date: "2013-04-25",
      source: "--",
      postingIsRental: false,
      time: 1366848000000,
      sellerAgent: null,
      showCountyLink: false,
      attributeSource: {
        infoString2: null,
        infoString3: null,
        infoString1: null,
      },
      pricePerSquareFoot: 542,
      buyerAgent: null,
      event: "Listed for sale",
      price: 975000,
    },
    {
      priceChangeRate: 0,
      date: "2013-04-16",
      source: "--",
      postingIsRental: false,
      time: 1366070400000,
      sellerAgent: null,
      showCountyLink: false,
      attributeSource: {
        infoString2: null,
        infoString3: null,
        infoString1: null,
      },
      pricePerSquareFoot: 542,
      buyerAgent: null,
      event: "Pending sale",
      price: 975000,
    },
    {
      priceChangeRate: 0,
      date: "2013-04-11",
      source: "--",
      postingIsRental: false,
      time: 1365638400000,
      sellerAgent: null,
      showCountyLink: false,
      attributeSource: {
        infoString2: null,
        infoString3: null,
        infoString1: null,
      },
      pricePerSquareFoot: 542,
      buyerAgent: null,
      event: "Listed for sale",
      price: 975000,
    },
    {
      priceChangeRate: 0,
      date: "2013-03-29",
      source: "--",
      postingIsRental: false,
      time: 1364515200000,
      sellerAgent: null,
      showCountyLink: false,
      attributeSource: {
        infoString2: null,
        infoString3: null,
        infoString1: null,
      },
      pricePerSquareFoot: 542,
      buyerAgent: null,
      event: "Pending sale",
      price: 975000,
    },
    {
      priceChangeRate: -0.024024024024024,
      date: "2013-02-23",
      source: "--",
      postingIsRental: false,
      time: 1361577600000,
      sellerAgent: null,
      showCountyLink: false,
      attributeSource: {
        infoString2: null,
        infoString3: null,
        infoString1: null,
      },
      pricePerSquareFoot: 542,
      buyerAgent: null,
      event: "Price change",
      price: 975000,
    },
    {
      priceChangeRate: -0.048571428571429,
      date: "2013-01-25",
      source: "--",
      postingIsRental: false,
      time: 1359072000000,
      sellerAgent: null,
      showCountyLink: false,
      attributeSource: {
        infoString2: null,
        infoString3: null,
        infoString1: null,
      },
      pricePerSquareFoot: 555,
      buyerAgent: null,
      event: "Price change",
      price: 999000,
    },
    {
      priceChangeRate: -0.041095890410959,
      date: "2013-01-10",
      source: "--",
      postingIsRental: false,
      time: 1357776000000,
      sellerAgent: null,
      showCountyLink: false,
      attributeSource: {
        infoString2: null,
        infoString3: null,
        infoString1: null,
      },
      pricePerSquareFoot: 583,
      buyerAgent: null,
      event: "Price change",
      price: 1050000,
    },
    {
      priceChangeRate: 0,
      date: "2012-11-28",
      source: "--",
      postingIsRental: false,
      time: 1354060800000,
      sellerAgent: null,
      showCountyLink: false,
      attributeSource: {
        infoString2: null,
        infoString3: null,
        infoString1: null,
      },
      pricePerSquareFoot: 608,
      buyerAgent: null,
      event: "Listed for sale",
      price: 1095000,
    },
  ],
  favoriteCount: 346,
  schools: [
    {
      link: "https://www.greatschools.org/school?id=02927&state=CA",
      rating: 6,
      totalCount: 1,
      distance: 0.4,
      assigned: null,
      name: "John Muir Elementary School",
      studentsPerTeacher: 18,
      isAssigned: true,
      size: 276,
      level: "Elementary",
      grades: "K-5",
      type: "Public",
    },
    {
      link: "https://www.greatschools.org/school?id=02919&state=CA",
      rating: 6,
      totalCount: 1,
      distance: 0.6,
      assigned: null,
      name: "John Adams Middle School",
      studentsPerTeacher: 20,
      isAssigned: true,
      size: 1022,
      level: "Middle",
      grades: "6-8",
      type: "Public",
    },
    {
      link: "https://www.greatschools.org/school?id=02932&state=CA",
      rating: 8,
      totalCount: 1,
      distance: 0.8,
      assigned: null,
      name: "Santa Monica High School",
      studentsPerTeacher: 32,
      isAssigned: true,
      size: 2857,
      level: "High",
      grades: "9-12",
      type: "Public",
    },
  ],
  zestimateHighPercent: "5",
  mlsid: "22-171535",
  address: {
    city: "Santa Monica",
    neighborhood: null,
    state: "CA",
    streetAddress: "737 Raymond Ave",
    zipcode: "90405",
  },
  city: "Santa Monica",
  providerListingID: null,
  country: "USA",
  currency: "USD",
  listed_by: {
    agent_reason: 3,
    zpro: true,
    recent_sales: null,
    review_count: null,
    display_name: "Justin Vold",
    badge_type: "Listing Agent",
    business_name: "Redfin",
    rating_average: null,
    phone: { prefix: "895", areacode: "310", number: "5025" },
    zuid: "X1-ZUz1ci99gqj409_uwi3",
    image_url: "https://www.zillowstatic.com/static/images/nophoto_h_n.png",
  },
  contingentListingType: null,
};

export const homesListTestData = {
  props: [
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 9147.6,
      address: "310 Linden Dr, Idaho Falls, ID 83401",
      imgSrc:
        "https://photos.zillowstatic.com/fp/4844b5881aaf4fc599c3b9a9a892b7bb-p_e.jpg",
      price: 315000,
      bedrooms: 3,
      longitude: -112.0109,
      latitude: 43.495193,
      listingStatus: "FOR_SALE",
      zpid: "76904444",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 2,
      livingArea: 2046,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "sqft",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 0.27,
      address: "3883 W Loxton Loop, Coeur D Alene, ID 83815",
      imgSrc:
        "https://photos.zillowstatic.com/fp/172bc22169a559bacee8018b10c67953-p_e.jpg",
      price: 565000,
      bedrooms: 4,
      longitude: -116.834076,
      latitude: 47.743267,
      listingStatus: "FOR_SALE",
      zpid: "113137830",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 2,
      livingArea: 2214,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "acres",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 0.75,
      address: "6997 W Maine St, Spirit Lake, ID 83869",
      imgSrc:
        "https://photos.zillowstatic.com/fp/afac605b2489428e960d796a30a8d7a0-p_e.jpg",
      price: 780000,
      bedrooms: 1,
      longitude: -116.87418,
      latitude: 47.96073,
      listingStatus: "FOR_SALE",
      zpid: "113146188",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 2,
      livingArea: 1167,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "acres",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 0.25,
      address: "11464 N Cattle Dr, Hayden Lake, ID 83835",
      imgSrc:
        "https://photos.zillowstatic.com/fp/68275d09acaaee4ad519e5bfa94c03d8-p_e.jpg",
      price: 849000,
      bedrooms: 3,
      longitude: -116.77221,
      latitude: 47.7769,
      listingStatus: "FOR_SALE",
      zpid: "113149278",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 2,
      livingArea: 2691,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "acres",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 8712,
      address: "1525 Claire View Ln, Idaho Falls, ID 83402",
      imgSrc:
        "https://photos.zillowstatic.com/fp/05153521a25eecbc2e80cdb750545b32-p_e.jpg",
      price: 285000,
      bedrooms: 3,
      longitude: -112.06031,
      latitude: 43.50374,
      listingStatus: "FOR_SALE",
      zpid: "76913068",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 1,
      livingArea: 2150,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "sqft",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 5357.88,
      address: "5559 W Elk Trail St, Boise, ID 83714",
      imgSrc:
        "https://photos.zillowstatic.com/fp/9b515404a263d47e8f5988bbdf90b64e-p_e.jpg",
      price: 425000,
      bedrooms: 3,
      longitude: -116.26117,
      latitude: 43.791965,
      listingStatus: "FOR_SALE",
      zpid: "306077221",
      listingSubType: { is_FSBA: true, is_openHouse: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 2,
      livingArea: 1427,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "sqft",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 1.8,
      address: "5336 S Bonnell Rd, Coeur D Alene, ID 83814",
      imgSrc:
        "https://photos.zillowstatic.com/fp/5a4670400576aae05ae169afe6d1f05a-p_e.jpg",
      price: 1595000,
      bedrooms: 4,
      longitude: -116.68435,
      latitude: 47.633385,
      listingStatus: "FOR_SALE",
      zpid: "204503763",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 4,
      livingArea: 3463,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "acres",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 0.31,
      address: "404 S Pinewood Dr, Post Falls, ID 83854",
      imgSrc:
        "https://photos.zillowstatic.com/fp/f38d0c4c54cc4d121d31a6eef00a9104-p_e.jpg",
      price: 475000,
      bedrooms: 5,
      longitude: -116.89728,
      latitude: 47.7024,
      listingStatus: "FOR_SALE",
      zpid: "113141014",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 3,
      livingArea: 2960,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "acres",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 7405.2,
      address: "3828 N Twin Eagles Way, Meridian, ID 83646",
      imgSrc:
        "https://photos.zillowstatic.com/fp/60871059a83271d1a6110bb46abaff34-p_e.jpg",
      price: 399900,
      bedrooms: 4,
      longitude: -116.41705,
      latitude: 43.639652,
      listingStatus: "FOR_SALE",
      zpid: "79622531",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 3,
      livingArea: 1624,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "sqft",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 7405.2,
      address: "505 W Cobblestone Pl, Nampa, ID 83651",
      imgSrc:
        "https://photos.zillowstatic.com/fp/ed4b7d08b4427e3a13c8d2d6b4521a76-p_e.jpg",
      price: 290000,
      bedrooms: 3,
      longitude: -116.58139,
      latitude: 43.574604,
      listingStatus: "FOR_SALE",
      zpid: "72354912",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 2,
      livingArea: 1484,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "sqft",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 2.25,
      address: "6 Rattlesnake Rd, Boise, ID 83716",
      imgSrc:
        "https://photos.zillowstatic.com/fp/e22b1cc7e41727492384ee2a8ae31b1e-p_e.jpg",
      price: 299900,
      bedrooms: 2,
      longitude: -115.99519,
      latitude: 43.75124,
      listingStatus: "FOR_SALE",
      zpid: "96136311",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 2,
      livingArea: 1141,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "acres",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 0.5,
      address: "1145 E Airport Rd, Blackfoot, ID 83221",
      imgSrc:
        "https://photos.zillowstatic.com/fp/0fd2242bb336da7ae41133f6d1ef9e5b-p_e.jpg",
      price: 395000,
      bedrooms: 4,
      longitude: -112.33425,
      latitude: 43.207653,
      listingStatus: "FOR_SALE",
      zpid: "119384654",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 3,
      livingArea: 2788,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "acres",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 0.29,
      address: "724 S Arthur Ave, Pocatello, ID 83204",
      imgSrc:
        "https://photos.zillowstatic.com/fp/fd2b811bf0f06bd7e499c4ffaea563f1-p_e.jpg",
      price: 279000,
      bedrooms: 3,
      longitude: -112.4458,
      latitude: 42.85684,
      listingStatus: "FOR_SALE",
      zpid: "113840608",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 2,
      livingArea: 2364,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "acres",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 10454.4,
      address: "1715 Cedar Dr, Lewiston, ID 83501",
      imgSrc:
        "https://photos.zillowstatic.com/fp/c75b312398c3511612290e98a50e60d9-p_e.jpg",
      price: 215000,
      bedrooms: 4,
      longitude: -116.94187,
      latitude: 46.374313,
      listingStatus: "FOR_SALE",
      zpid: "110329012",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 2,
      livingArea: 1989,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "sqft",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 0.9,
      address: "520 Highway 52, Horseshoe Bend, ID 83629",
      imgSrc:
        "https://photos.zillowstatic.com/fp/8f149ccbc8742803154a57ec1f0f8b48-p_e.jpg",
      price: 375000,
      bedrooms: 3,
      longitude: -116.198814,
      latitude: 43.917103,
      listingStatus: "FOR_SALE",
      zpid: "96134798",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 2,
      livingArea: 2103,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "acres",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 6969.6,
      address: "707 9th Ave S, Nampa, ID 83651",
      imgSrc:
        "https://photos.zillowstatic.com/fp/c5009cc8b269494dac8693b448df29d1-p_e.jpg",
      price: 269900,
      bedrooms: 2,
      longitude: -116.56942,
      latitude: 43.576344,
      listingStatus: "FOR_SALE",
      zpid: "72313291",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 1,
      livingArea: 1522,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "sqft",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 7405.2,
      address: "875 Eagles Rest Dr, Driggs, ID 83422",
      imgSrc:
        "https://photos.zillowstatic.com/fp/c2831157a901f85dc5abeaa31f0c1c9e-p_e.jpg",
      price: 599000,
      bedrooms: 3,
      longitude: -111.10681,
      latitude: 43.710335,
      listingStatus: "FOR_SALE",
      zpid: "126403817",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 2,
      livingArea: 1552,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "sqft",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 0.56,
      address: "14 Bessie Dr, Boise, ID 83716",
      imgSrc:
        "https://photos.zillowstatic.com/fp/8abf5d61c162d0053f524cc3e2923bdb-p_e.jpg",
      price: 254000,
      bedrooms: 2,
      longitude: -116.045586,
      latitude: 43.639084,
      listingStatus: "FOR_SALE",
      zpid: "89948518",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 1,
      livingArea: 1244,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "acres",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 0.28,
      address: "2950 W Pebblestone St, Meridian, ID 83646",
      imgSrc:
        "https://photos.zillowstatic.com/fp/dcef9df546aeac5f9ab49e08d028bf62-p_e.jpg",
      price: 379900,
      bedrooms: 3,
      longitude: -116.43052,
      latitude: 43.63369,
      listingStatus: "FOR_SALE",
      zpid: "79685174",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 2,
      livingArea: 1548,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "acres",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 10,
      address: "321 Wildflower Rd, Saint Maries, ID 83861",
      imgSrc:
        "https://photos.zillowstatic.com/fp/557746c6fd701c46a3bb83be5067a1a1-p_e.jpg",
      price: 190000,
      bedrooms: 1,
      longitude: -116.64897,
      latitude: 47.267017,
      listingStatus: "FOR_SALE",
      zpid: "334417091",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 1,
      livingArea: 700,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "acres",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 1.37,
      address: "201 Helm Dr, Horseshoe Bend, ID 83629",
      imgSrc:
        "https://photos.zillowstatic.com/fp/58858495df468fc7b9c193b619f09943-p_e.jpg",
      price: 575000,
      bedrooms: 3,
      longitude: -116.199646,
      latitude: 43.914444,
      listingStatus: "FOR_SALE",
      zpid: "89899027",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 3,
      livingArea: 2720,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "acres",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 11.54,
      address: "2833 Hoo Doo Mountain Rd, Priest River, ID 83856",
      imgSrc:
        "https://photos.zillowstatic.com/fp/d29f1939d827e1664039804130f30a1f-p_e.jpg",
      price: 499000,
      bedrooms: 2,
      longitude: -116.87411,
      latitude: 48.09631,
      listingStatus: "FOR_SALE",
      zpid: "103899097",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 1,
      livingArea: 1500,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "acres",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 9583.2,
      address: "2764 S Velvet Falls Way, Meridian, ID 83642",
      imgSrc:
        "https://photos.zillowstatic.com/fp/6cc73cd248ed61d13384605052a02c17-p_e.jpg",
      price: 514900,
      bedrooms: 4,
      longitude: -116.375694,
      latitude: 43.580044,
      listingStatus: "FOR_SALE",
      zpid: "79646828",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 3,
      livingArea: 2155,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "sqft",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "MANUFACTURED",
      lotAreaValue: 0,
      address: "2081 W Yorkshire Ave, Coeur D Alene, ID 83815",
      imgSrc:
        "https://photos.zillowstatic.com/fp/6d2109836ba44b3400f3500f5f46163d-p_e.jpg",
      price: 220000,
      bedrooms: 3,
      longitude: -116.814095,
      latitude: 47.721985,
      listingStatus: "FOR_SALE",
      zpid: "113108358",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 2,
      livingArea: 1296,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "sqft",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 8276.4,
      address: "2073 W Lake Pointe Ct, Nampa, ID 83651",
      imgSrc:
        "https://photos.zillowstatic.com/fp/67bf5f53895cc167c9a7cdfc3df74cfe-p_e.jpg",
      price: 375000,
      bedrooms: 4,
      longitude: -116.606255,
      latitude: 43.579903,
      listingStatus: "FOR_SALE",
      zpid: "72312626",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 3,
      livingArea: 2117,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "sqft",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 0.38,
      address: "27 Lowman Home Rd, Lowman, ID 83637",
      imgSrc:
        "https://photos.zillowstatic.com/fp/6606e0322a667f667720f18967ef4dc1-p_e.jpg",
      price: 175000,
      bedrooms: 3,
      longitude: -116.0085,
      latitude: 43.72458,
      listingStatus: "FOR_SALE",
      zpid: "89942200",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 1,
      livingArea: 727,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "acres",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 0.4,
      address: "2204 N 9th St, Coeur D Alene, ID 83814",
      imgSrc:
        "https://photos.zillowstatic.com/fp/20998d4d2f40e463a9b68778198644a7-p_e.jpg",
      price: 399900,
      bedrooms: 5,
      longitude: -116.772385,
      latitude: 47.697456,
      listingStatus: "FOR_SALE",
      zpid: "113107249",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 2,
      livingArea: 2576,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "acres",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 27.8,
      address: "237 Pine Ridge Rd, White Bird, ID 83554",
      imgSrc:
        "https://photos.zillowstatic.com/fp/1abeaf221b618a1d1f2d95c4bce4f0f0-p_e.jpg",
      price: 479900,
      bedrooms: 4,
      longitude: -116.371635,
      latitude: 45.763863,
      listingStatus: "FOR_SALE",
      zpid: "115523946",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 2,
      livingArea: 2256,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "acres",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 8.45,
      address: "127 Chief Joseph Ln, Samuels, ID 83864",
      imgSrc:
        "https://photos.zillowstatic.com/fp/c9722697faf516a35491be85214941c0-p_e.jpg",
      price: 495000,
      bedrooms: 2,
      longitude: -116.446915,
      latitude: 48.450294,
      listingStatus: "FOR_SALE",
      zpid: "221473437",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 2,
      livingArea: 1200,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "acres",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 8276.4,
      address: "1004 Skyline Pl, Caldwell, ID 83605",
      imgSrc:
        "https://photos.zillowstatic.com/fp/4392afb7069823b03ed0c9b778463299-p_e.jpg",
      price: 329900,
      bedrooms: 4,
      longitude: -116.66837,
      latitude: 43.678024,
      listingStatus: "FOR_SALE",
      zpid: "72357588",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 2,
      livingArea: 1836,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "sqft",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 10.1,
      address: "1670 Flannigan Creek Rd, Potlatch, ID 83855",
      imgSrc:
        "https://photos.zillowstatic.com/fp/56950a706e14b12618a7a82f473abe31-p_e.jpg",
      price: 439000,
      bedrooms: 3,
      longitude: -116.920975,
      latitude: 46.92469,
      listingStatus: "FOR_SALE",
      zpid: "110451624",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 2,
      livingArea: 2696,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "acres",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 6969.6,
      address: "3320 S Oxbow Dr, Nampa, ID 83686",
      imgSrc:
        "https://photos.zillowstatic.com/fp/ae9890bbd8937e4f13501320349e5538-p_e.jpg",
      price: 385000,
      bedrooms: 5,
      longitude: -116.58968,
      latitude: 43.53692,
      listingStatus: "FOR_SALE",
      zpid: "72323247",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 3,
      livingArea: 2715,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "sqft",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 0.27,
      address: "2813 E Castleberg Loop, Nampa, ID 83686",
      imgSrc:
        "https://photos.zillowstatic.com/fp/af5cece26546fe108992b114fba0dc2f-p_e.jpg",
      price: 399000,
      bedrooms: 4,
      longitude: -116.53649,
      latitude: 43.550697,
      listingStatus: "FOR_SALE",
      zpid: "72365573",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 3,
      livingArea: 1905,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "acres",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 8712,
      address: "2089 W Sandalwood Dr, Meridian, ID 83646",
      imgSrc:
        "https://photos.zillowstatic.com/fp/9d4450d8c7a86ed9990a9e158768a931-p_e.jpg",
      price: 440900,
      bedrooms: 3,
      longitude: -116.419685,
      latitude: 43.62377,
      listingStatus: "FOR_SALE",
      zpid: "79520262",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 3,
      livingArea: 1793,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "sqft",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 4.016,
      address: "148 Pine Rd, Kamiah, ID 83536",
      imgSrc:
        "https://photos.zillowstatic.com/fp/d48ad36c92dd4834f21ac8a235dfbecf-p_e.jpg",
      price: 330000,
      bedrooms: 4,
      longitude: -116.02186,
      latitude: 46.203697,
      listingStatus: "FOR_SALE",
      zpid: "115520970",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 2,
      livingArea: 3434,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "acres",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 0.39,
      address: "1229 W Avalon St, Kuna, ID 83634",
      imgSrc:
        "https://photos.zillowstatic.com/fp/2c0772a8d35ac4d88d63878ba89531ac-p_e.jpg",
      price: 259000,
      bedrooms: 2,
      longitude: -116.428925,
      latitude: 43.48813,
      listingStatus: "FOR_SALE",
      zpid: "79687128",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 2,
      livingArea: 1596,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "acres",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 1.09,
      address: "8782 N Yellowstone Hwy, Idaho Falls, ID 83401",
      imgSrc:
        "https://photos.zillowstatic.com/fp/a64d207e76e881334c31c6a7198eb949-p_e.jpg",
      price: 475000,
      bedrooms: 4,
      longitude: -111.96321,
      latitude: 43.57432,
      listingStatus: "FOR_SALE",
      zpid: "76918305",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 2,
      livingArea: 2958,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "acres",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 8712,
      address: "16788 N Kettering Ln, Nampa, ID 83687",
      imgSrc:
        "https://photos.zillowstatic.com/fp/987533eebd1d6ffee206242448506a44-p_e.jpg",
      price: 299000,
      bedrooms: 2,
      longitude: -116.53947,
      latitude: 43.61651,
      listingStatus: "FOR_SALE",
      zpid: "72325398",
      listingSubType: { is_foreclosure: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 2,
      livingArea: 1254,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "sqft",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 0.4,
      address: "3290 W Fairway Dr, Coeur D Alene, ID 83815",
      imgSrc:
        "https://photos.zillowstatic.com/fp/cba7cfe27c51fb463c315d3ef0ff029e-p_e.jpg",
      price: 624900,
      bedrooms: 3,
      longitude: -116.82538,
      latitude: 47.707314,
      listingStatus: "FOR_SALE",
      zpid: "113118016",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 3,
      livingArea: 2432,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "acres",
      hasImage: true,
    },
    {
      dateSold: null,
      propertyType: "SINGLE_FAMILY",
      lotAreaValue: 10018.8,
      address: "2957 E Anemone Ct, Boise, ID 83716",
      imgSrc:
        "https://photos.zillowstatic.com/fp/73f1a4d59e7bd7feb9c53009b30a5345-p_e.jpg",
      price: 390000,
      bedrooms: 3,
      longitude: -116.147385,
      latitude: 43.55298,
      listingStatus: "FOR_SALE",
      zpid: "79596202",
      listingSubType: { is_FSBA: true },
      contingentListingType: null,
      daysOnZillow: -1,
      bathrooms: 2,
      livingArea: 1124,
      country: "USA",
      currency: "USD",
      lotAreaUnit: "sqft",
      hasImage: true,
    },
  ],
  resultsPerPage: 40,
  totalPages: 20,
  totalResultCount: 13799,
  currentPage: 1,
};
