name: package lambda and deploy lambda  

on: 
  push:
    branches:
    - API
    
jobs:

  deploy_source:
    name: deploy lambda from source 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: checkout source code 
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-duration-seconds: 1200
          role-session-name: MySessionName
      - run: cd server/realtor-api/ && sam build
      - run: sam package --s3-bucket realtor-api-prod --output-template-file output.yaml
      - run: sam deploy --template-file output.yaml --stack-name realtor-app --capabilities CAPABILITY_IAM 
        
        
      
