name: build and deploy next.js client 

on: 
  push:
    branches:
    - Client
    
jobs:

  deploy_source:
    name: deployment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: checkout source code 
        uses: actions/checkout@v3
      - name: install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-duration-seconds: 1200
          role-session-name: MySessionName
      - run: cd client && aws s3 cp /Users/dariusdeah/source/FullStack-TS/realtor-app/client/out/ ${{secrets.S3_URI}} --recursive
